import React, { useState, useRef } from "react";

const QUESTIONS = [
  // SET A (1-25)
  { id:1, set:"A", q:"The 8086 microprocessor is classified as a:", opts:["8-bit processor","16-bit processor","32-bit processor","64-bit processor","4-bit processor"], ans:1, exp:"8086 معالج 16-بت؛ عرض وحدة المعالجة والسجلات العامة الأساسية فيه 16 بت." },
  { id:2, set:"A", q:"The maximum memory that 8086 can address is:", opts:["64 KB","128 KB","256 KB","1 MB","4 GB"], ans:3, exp:"ناقل العناوين 20 بت، وبالتالي أقصى فضاء عنونة = 2^20 = 1 MB." },
  { id:3, set:"A", q:"The address bus size of the 8086 is:", opts:["8-bit","16-bit","18-bit","20-bit","32-bit"], ans:3, exp:"8086 يملك Address Bus بعرض 20 بت." },
  { id:4, set:"A", q:"The 8086 can support up to how many I/O ports?", opts:["256","1K","8K","32K","64K"], ans:4, exp:"عنونة منافذ الإدخال/الإخراج في 8086 تتم بعرض 16 بت، أي 2^16 = 65536 = 64K منفذاً." },
  { id:5, set:"A", q:"The 8086 operates in which two modes?", opts:["User and Kernel","Real and Protected","Minimum and Maximum","Master and Slave","Input and Output"], ans:2, exp:"للـ 8086 نمطان للتشغيل: Minimum mode و Maximum mode." },
  { id:6, set:"A", q:"The 8086 architecture is divided into:", opts:["ALU and Control Unit","BIU and EU","Memory and I/O","Stack and Heap","ROM and RAM"], ans:1, exp:"البنية تنقسم إلى Bus Interface Unit و Execution Unit." },
  { id:7, set:"A", q:"The instruction queue in 8086 can store up to:", opts:["2 bytes","4 bytes","6 bytes","8 bytes","10 bytes"], ans:2, exp:"طابور الجلب المسبق في 8086 سعته 6 بايت." },
  { id:8, set:"A", q:"The main purpose of the instruction queue is to:", opts:["Increase memory size","Store data permanently","Implement pipelining","Reduce power consumption","Store flags"], ans:2, exp:"الطابور يحقق الجلب المسبق للتعليمات لتحسين الأداء بطريقة شبيهة بالـ pipeline." },
  { id:9, set:"A", q:"The physical address in 8086 is generated by:", opts:["ALU","EU","Stack Pointer","BIU","Flag Register"], ans:3, exp:"الـ BIU هو المسؤول عن تكوين العنوان الفيزيائي والتعامل مع الحافلة." },
  { id:10, set:"A", q:"When a jump instruction is executed, the BIU will:", opts:["Halt execution","Reset the instruction queue","Disable interrupts","Clear flags","Stop pipelining permanently"], ans:1, exp:"عند القفز تتغير سلسلة التنفيذ، لذلك تُفرَّغ/تُعاد تهيئة طابور التعليمات." },
  { id:11, set:"A", q:"Which of the following is known as the Accumulator register?", opts:["BX","CX","DX","AX","SP"], ans:3, exp:"السجل AX هو Accumulator register." },
  { id:12, set:"A", q:"Which register is primarily used as a loop counter?", opts:["AX","BX","CX","DX","SI"], ans:2, exp:"السجل CX يُستخدم عادةً كعدّاد للحلقات." },
  { id:13, set:"A", q:"The Stack Pointer (SP) is associated with which segment register?", opts:["CS","DS","ES","SS","IP"], ans:3, exp:"السجل SP يرتبط بمقطع المكدس Stack Segment أي SS." },
  { id:14, set:"A", q:"In string operations, SI is associated with:", opts:["CS","DS","SS","ES","IP"], ans:1, exp:"في عمليات السلاسل SI يكون عادةً مع DS كمصدر." },
  { id:15, set:"A", q:"The Flag register in 8086 contains how many active flags?", opts:["6","7","8","9","16"], ans:3, exp:"في 8086 توجد 9 أعلام فعّالة مستخدمة فعلياً." },
  { id:16, set:"A", q:"Which flag is set when the result of an operation is zero?", opts:["CF","OF","ZF","SF","PF"], ans:2, exp:"Zero Flag ZF يُضبط عندما تكون نتيجة العملية صفراً." },
  { id:17, set:"A", q:"The Carry Flag (CF) is set when:", opts:["Result is negative","Result is zero","There is a carry out of MSB","Parity is even","Overflow occurs only"], ans:2, exp:"Carry Flag يرتفع عند حدوث حمل من أعلى بت في العمليات الموجبة." },
  { id:18, set:"A", q:"The Direction Flag (DF) controls:", opts:["Interrupt handling","Arithmetic overflow","String auto increment/decrement","Parity checking","Stack operations"], ans:2, exp:"Direction Flag يحدد زيادة/إنقاص SI و DI في تعليمات السلاسل." },
  { id:19, set:"A", q:"Each segment in 8086 has a maximum size of:", opts:["16 KB","32 KB","64 KB","128 KB","1 MB"], ans:2, exp:"حجم كل Segment في 8086 يساوي 64 كيلوبايت كحد أقصى." },
  { id:20, set:"A", q:"The physical address is calculated as:", opts:["Segment + Offset","Segment × 10H + Offset","Segment × 16 + Offset","Segment ÷ Offset","Offset × 16"], ans:2, exp:"العنوان الفيزيائي = Segment × 10H + Offset. (الخيار C مكافئ أيضاً)" },
  { id:21, set:"A", q:"If CS = 2000H and IP = 1000H, the physical address is:", opts:["21000H","30000H","210000H","20000H","10000H"], ans:0, exp:"الحساب: 2000H × 10H = 20000H + 1000H = 21000H." },
  { id:22, set:"A", q:"A word is aligned when its least significant byte is stored at:", opts:["Odd address","Even address","Multiple of 3","High bank only","Low bank only"], ans:1, exp:"تكون الكلمة aligned عندما يبدأ البايت الأقل أهمية عند عنوان زوجي." },
  { id:23, set:"A", q:"A misaligned word in 8086 requires:", opts:["1 bus cycle","2 bus cycles","3 bus cycles","4 bus cycles","No bus cycle"], ans:1, exp:"الكلمة غير المحاذية تحتاج غالباً إلى دورتين على الـ bus." },
  { id:24, set:"A", q:"In 8086 memory banking, the high bank is enabled when:", opts:["A0 = 0","BHE = 1","BHE = 0","A1 = 1","CF = 1"], ans:2, exp:"تفعيل البنك العالي يتم بإشارة BHE = 0 (فعالة بالمستوى المنخفض)." },
  { id:25, set:"A", q:"The program that translates assembly language into machine language is called:", opts:["Compiler","Interpreter","Loader","Assembler","Linker"], ans:3, exp:"الـ Assembler يترجم Assembly إلى Machine Code." },

  // SET B (26-75)
  { id:26, set:"B", q:"The Intel 8086 microprocessor is classified as a:", opts:["8-bit processor","16-bit processor","32-bit processor","64-bit processor","4-bit processor"], ans:1, exp:"8086 مصنف كمعالج 16-بت." },
  { id:27, set:"B", q:"The 8086 has an address bus width of:", opts:["8 bits","16 bits","20 bits","24 bits","32 bits"], ans:2, exp:"عرض ناقل العناوين هو 20 بت." },
  { id:28, set:"B", q:"The maximum memory that the 8086 can address is:", opts:["64 KB","256 KB","512 KB","1 MB","4 MB"], ans:3, exp:"الذاكرة القصوى القابلة للعنونة هي 1 ميجابايت." },
  { id:29, set:"B", q:"The number of I/O ports supported by the 8086 is:", opts:["8K","16K","32K","64K","128K"], ans:3, exp:"عدد منافذ I/O الممكنة هو 64K." },
  { id:30, set:"B", q:"The multiplexed bus in 8086 includes:", opts:["A0-A7","AD0-AD15","D0-D7","A8-A15","BHE-ALE"], ans:1, exp:"الخطوط AD0-AD15 هي خطوط متعددة الإرسال للعنوان/البيانات." },
  { id:31, set:"B", q:"The 8086 operates in how many modes?", opts:["One","Two","Three","Four","Five"], ans:1, exp:"للـ 8086 نمطان: Minimum و Maximum." },
  { id:32, set:"B", q:"Minimum mode in 8086 is used for:", opts:["Multiprocessor systems","Single processor systems","Network systems","Embedded systems","Parallel processors"], ans:1, exp:"Minimum mode مخصص للأنظمة أحادية المعالج." },
  { id:33, set:"B", q:"Maximum mode in 8086 is used for:", opts:["Single microprocessor systems","Multiprocessor systems","Portable devices","Robotics","Gaming systems"], ans:1, exp:"Maximum mode يُستخدم مع الأنظمة متعددة المعالجات/المعالجات المساعدة." },
  { id:34, set:"B", q:"The instruction queue in 8086 can prefetch up to:", opts:["2 bytes","4 bytes","6 bytes","8 bytes","10 bytes"], ans:2, exp:"طابور الجلب المسبق سعته 6 بايت." },
  { id:35, set:"B", q:"The supply voltage required for 8086 operation is:", opts:["+3V","+5V","+9V","+12V","+15V"], ans:1, exp:"جهد تشغيل 8086 القياسي هو +5V." },
  { id:36, set:"B", q:"The two major units of 8086 architecture are:", opts:["ALU and CU","BIU and EU","RAM and ROM","Cache and ALU","Stack and Queue"], ans:1, exp:"الوحدتان الرئيسيتان هما BIU و EU." },
  { id:37, set:"B", q:"The Bus Interface Unit (BIU) is responsible for:", opts:["Instruction execution","Memory addressing","Arithmetic operations","Logic operations","Interrupt handling"], ans:1, exp:"الـ BIU يتولى التعامل مع العناوين والذاكرة والحافلة." },
  { id:38, set:"B", q:"The Execution Unit (EU) is responsible for:", opts:["Instruction fetching","Instruction execution","Memory addressing","Bus control","I/O mapping"], ans:1, exp:"الـ EU مسؤول عن فك وتنفيذ التعليمات." },
  { id:39, set:"B", q:"The pipelining mechanism in 8086 improves:", opts:["Memory capacity","System performance","Instruction size","Voltage stability","Clock accuracy"], ans:1, exp:"الجلب المسبق والـ pipeline يحسنان الأداء العام." },
  { id:40, set:"B", q:"The instruction queue works as:", opts:["LIFO","FIFO","Stack","Register file","Cache"], ans:1, exp:"طابور التعليمات يعمل كمبدأ First In First Out." },
  { id:41, set:"B", q:"The segment register used for instructions is:", opts:["DS","ES","CS","SS","IP"], ans:2, exp:"Segment التعليمات هو Code Segment أي CS." },
  { id:42, set:"B", q:"The register that contains the offset of the next instruction is:", opts:["CS","IP","SP","AX","BX"], ans:1, exp:"السجل IP يحوي إزاحة التعليمة التالية." },
  { id:43, set:"B", q:"Which segment register is used for stack operations?", opts:["CS","DS","SS","ES","IP"], ans:2, exp:"عمليات المكدس تستخدم Stack Segment أي SS." },
  { id:44, set:"B", q:"The extra segment register is abbreviated as:", opts:["XS","ES","SS","DS","CS"], ans:1, exp:"اختصار Extra Segment هو ES." },
  { id:45, set:"B", q:"The physical address in 8086 is:", opts:["8 bits","12 bits","16 bits","20 bits","32 bits"], ans:3, exp:"العنوان الفيزيائي في 8086 عرضه 20 بت." },
  { id:46, set:"B", q:"Logical address in 8086 is written as:", opts:["offset:segment","segment:offset","base:index","address:data","data:address"], ans:1, exp:"العنوان المنطقي يُكتب بالشكل segment:offset." },
  { id:47, set:"B", q:"The size of each memory segment in 8086 is:", opts:["32 KB","64 KB","128 KB","256 KB","512 KB"], ans:1, exp:"كل Segment سعته 64KB." },
  { id:48, set:"B", q:"The number of segments active at a time in 8086 is:", opts:["2","3","4","5","6"], ans:2, exp:"القطاعات الفعالة المعتادة هي 4: CS و DS و SS و ES." },
  { id:49, set:"B", q:"The formula for calculating physical address is:", opts:["Segment + Offset","Segment × 10H + Offset","Segment × Offset","Offset × 10H + Segment","Segment ÷ Offset"], ans:1, exp:"هذه الصيغة تكافئ Segment × 16 + Offset." },
  { id:50, set:"B", q:"Which unit generates the physical address?", opts:["EU","BIU","ALU","Stack unit","Flag unit"], ans:1, exp:"وحدة BIU تولد العنوان الفيزيائي." },
  { id:51, set:"B", q:"The register AX is mainly used as:", opts:["Base register","Counter register","Accumulator","Pointer register","Index register"], ans:2, exp:"AX هو السجل التراكمي الأساسي Accumulator." },
  { id:52, set:"B", q:"The BX register is commonly used as:", opts:["Base register","Stack register","Flag register","Instruction register","Control register"], ans:0, exp:"BX يُستخدم غالباً كسجل قاعدة Base register." },
  { id:53, set:"B", q:"The CX register is commonly used as:", opts:["Counter register","Accumulator","Segment register","Index register","Stack register"], ans:0, exp:"CX هو عداد شائع للحلقات والتكرار Counter register." },
  { id:54, set:"B", q:"The DX register is used in:", opts:["Multiplication and division","Loop operations","Stack operations","Interrupt control","Instruction decoding"], ans:0, exp:"DX يُستخدم مع AX في الضرب والقسمة وبعض عمليات I/O." },
  { id:55, set:"B", q:"SP register stands for:", opts:["Source Pointer","Stack Pointer","System Pointer","Segment Pointer","Special Pointer"], ans:1, exp:"SP اختصار Stack Pointer." },
  { id:56, set:"B", q:"BP register is mainly used for:", opts:["Stack data access","Instruction fetch","Arithmetic logic","Interrupt control","Flag manipulation"], ans:0, exp:"BP يُستخدم للوصول إلى بيانات المكدس Stack data access." },
  { id:57, set:"B", q:"SI register stands for:", opts:["Source Index","Segment Index","System Index","Stack Index","Special Index"], ans:0, exp:"SI اختصار Source Index." },
  { id:58, set:"B", q:"DI register stands for:", opts:["Data Index","Destination Index","Direct Index","Dynamic Index","Dual Index"], ans:1, exp:"DI اختصار Destination Index." },
  { id:59, set:"B", q:"The flag register in 8086 contains:", opts:["8 flags","9 flags","10 flags","12 flags","16 flags"], ans:1, exp:"المقصود الأعلام الفعالة في 8086 وعددها 9." },
  { id:60, set:"B", q:"The Zero Flag (ZF) is set when:", opts:["Result is negative","Result is zero","Carry occurs","Overflow occurs","Parity changes"], ans:1, exp:"ZF يرتفع عندما تكون النتيجة صفراً." },
  { id:61, set:"B", q:"The Carry Flag (CF) indicates:", opts:["Zero result","Borrow or carry","Sign change","Interrupt","Overflow"], ans:1, exp:"CF يدل على حمل أو استعارة في العمليات الحسابية." },
  { id:62, set:"B", q:"The Sign Flag (SF) represents:", opts:["Carry result","Parity result","Sign of result","Stack condition","Interrupt enable"], ans:2, exp:"SF يعكس إشارة النتيجة Sign of result." },
  { id:63, set:"B", q:"The Direction Flag (DF) controls:", opts:["Interrupts","String operations direction","Arithmetic operations","Stack operations","Memory size"], ans:1, exp:"DF يتحكم باتجاه المعالجة في تعليمات السلاسل." },
  { id:64, set:"B", q:"Overflow Flag (OF) indicates:", opts:["Division error","Arithmetic overflow","Memory error","Stack overflow","Interrupt"], ans:1, exp:"OF يدل على overflow في العمليات الموقعة." },
  { id:65, set:"B", q:"Register addressing mode means:", opts:["Operand is in memory","Operand is in register","Operand is immediate","Operand is constant","Operand is stack"], ans:1, exp:"في Register addressing يكون المعامل داخل سجل." },
  { id:66, set:"B", q:"Immediate addressing mode means:", opts:["Operand in memory","Operand in register","Operand is constant value","Operand in stack","Operand in segment"], ans:2, exp:"Immediate addressing يعني أن القيمة ثابتة داخل التعليمة." },
  { id:67, set:"B", q:"Direct addressing mode means:", opts:["Address stored in register","Address given directly in instruction","Address stored in stack","Address in segment","Address in flag"], ans:1, exp:"Direct addressing: العنوان يُذكر مباشرة في التعليمة." },
  { id:68, set:"B", q:"Aligned word in memory occurs when:", opts:["Address is odd","Address is even","Address is negative","Address is large","Address is zero"], ans:1, exp:"الكلمة aligned تبدأ عند عنوان زوجي." },
  { id:69, set:"B", q:"Misaligned word requires:", opts:["One bus cycle","Two bus cycles","Three bus cycles","Four bus cycles","Five bus cycles"], ans:1, exp:"الكلمة غير المحاذية تحتاج دورتين عادةً." },
  { id:70, set:"B", q:"8086 memory banks are divided into:", opts:["Two 512KB banks","Two 1MB banks","Four 256KB banks","Eight 128KB banks","Single 1MB bank"], ans:0, exp:"تقسم الذاكرة إلى بنكين كل منهما 512KB: منخفض وعالٍ." },
  { id:71, set:"B", q:"The lower memory bank handles:", opts:["Odd addresses","Even addresses","Both addresses","Segment addresses","Stack addresses"], ans:1, exp:"البنك المنخفض يتعامل مع العناوين الزوجية." },
  { id:72, set:"B", q:"The high memory bank handles:", opts:["Even addresses","Odd addresses","Segment addresses","Stack addresses","Interrupt addresses"], ans:1, exp:"البنك العالي يتعامل مع العناوين الفردية." },
  { id:73, set:"B", q:"Assembly language uses:", opts:["Binary codes","Mnemonics","Machine numbers","Electrical pulses","Logic gates"], ans:1, exp:"لغة التجميع تستخدم رموز مختصرة Mnemonics." },
  { id:74, set:"B", q:"An assembler converts:", opts:["Machine code to assembly","Assembly to machine code","Binary to decimal","Decimal to binary","Hardware to software"], ans:1, exp:"وظيفة الـ Assembler تحويل Assembly إلى Machine Code." },
  { id:75, set:"B", q:"The MOV instruction is used for:", opts:["Arithmetic","Data transfer","Loop control","Interrupt","Branching"], ans:1, exp:"MOV لنقل البيانات Data transfer." },

  // SET C (76-100)
  { id:76, set:"C", q:"The Microprocessor 8086 registers is:", opts:["8 bit","16 bit","32 bit","64 bit","128 bit"], ans:1, exp:"سجلات 8086 العامة الأساسية بعرض 16 بت." },
  { id:77, set:"C", q:"The Microprocessor 8086 requires a power supply:", opts:["+5V","+12V","+1.5V","+9V","+10V"], ans:0, exp:"يحتاج 8086 إلى مصدر تغذية +5V." },
  { id:78, set:"C", q:"The instruction queue in Microprocessor 8086 is a part of:", opts:["EU","BIU","ALU","Registers","CU"], ans:1, exp:"Instruction Queue جزء من الـ BIU." },
  { id:79, set:"C", q:"The BIU contains the following register:", opts:["DI","BP","IP","SI","AX"], ans:2, exp:"من سجلات الـ BIU: IP مع سجلات المقاطع." },
  { id:80, set:"C", q:"If DS = 7FA2H and offset = 438EH, the physical address is:", opts:["83DAEH","7FA2:438E","7FA20H","8FA1FH","5AF31H"], ans:0, exp:"الحساب: 7FA2H × 10H = 7FA20H + 438EH = 83DAEH." },
  { id:81, set:"C", q:"If CS = 24F6H and IP = 634AH, the logical address is:", opts:["634A","24F6:634A","24F60","34F5F","5634C"], ans:1, exp:"هذا هو تمثيل العنوان المنطقي بصيغة segment:offset." },
  { id:82, set:"C", q:"In Register addressing mode if AX = 1000H and BL = 50H, what will be the value of AX after executing ADD AX, BX?", opts:["AX = 1050H","AX = 15FFH","AX = 1080H","AX = 10ACH","AX = 15AAH"], ans:0, exp:"عادة المقصود BX = 0050H عند إعطاء BL=50H، لذا 1000H + 0050H = 1050H." },
  { id:83, set:"C", q:"Memory size of microprocessor 8086 is:", opts:["1M","2M","3M","4M","5M"], ans:0, exp:"سعة الذاكرة القابلة للعنونة هي 1 ميجابايت." },
  { id:84, set:"C", q:"Number of transistors in microprocessor 8086 are:", opts:["4500","6500","29000","130000","2200"], ans:2, exp:"عدد الترانزستورات الشائع ذكره للـ 8086 يقارب 29 ألفاً." },
  { id:85, set:"C", q:"The responsible for decoding and executing all instruction:", opts:["Bus interface unit (BIU)","Execution unit (EU)","Register","Pipelining","ALU"], ans:1, exp:"الـ EU يفك وينفذ التعليمات." },
  { id:86, set:"C", q:"Used to store information temporarily in the CPU:", opts:["ROM","Cache memory","Register","Storage","RAM"], ans:2, exp:"السجلات تخزن المعلومات مؤقتاً داخل المعالج." },
  { id:87, set:"C", q:"Used as a loop counter:", opts:["AX","BX","CX","DX","SS"], ans:2, exp:"CX هو العداد المفضل للحلقات." },
  { id:88, set:"C", q:"Preferred register to use in arithmetic, logic and data transfer instruction:", opts:["AX","BX","CX","DX","IR"], ans:0, exp:"AX هو السجل المفضل كثيراً في الحساب والمنطق ونقل البيانات." },
  { id:89, set:"C", q:"Represent an independently addressable unit of memory consisting of 64K consecutive bytes:", opts:["Pipeline","Logical address","Physical address","Segment","Register"], ans:3, exp:"الـ Segment يمثل 64KB من البايتات المتتالية." },
  { id:90, set:"C", q:"If CS = 24F6H and IP = 634AH, the upper range is:", opts:["24F6:634A","634A","34F5F","24F60","76340"], ans:2, exp:"المدى الأعلى للقطاع = 24F60H + FFFFH = 34F5FH." },
  { id:91, set:"C", q:"MOV AL, BL is an example of:", opts:["Immediate addressing mode","Register addressing mode","Indexed addressing mode","Direct addressing mode","Indirect addressing mode"], ans:1, exp:"في MOV AL, BL كلا المعاملين سجلات." },
  { id:92, set:"C", q:"AX = 2345H, what will be the value of AX after executing MOV AL, 07H?", opts:["AX = 2345H","AX = 4523H","AX = 2307H","AX = 0723H","AX = 8462H"], ans:2, exp:"التعليمة تغيّر AL فقط إلى 07H وتبقي AH = 23H." },
  { id:93, set:"C", q:"MOV [1000], AX is an example of:", opts:["Register addressing mode","Immediate addressing mode","Indexed addressing mode","Direct addressing mode","Indirect addressing mode"], ans:3, exp:"العنوان [1000] مذكور مباشرة داخل التعليمة = Direct addressing mode." },
  { id:94, set:"C", q:"Based addressing mode uses one of two base registers:", opts:["SI or DI","BX or BP","DS or BP","SS or SI","DI or SS"], ans:1, exp:"Based addressing يستخدم أحد سجلي القاعدة BX أو BP." },
  { id:95, set:"C", q:"SI or DI are used in the operand field with:", opts:["Register addressing mode","Indexed addressing mode","Direct addressing mode","Immediate addressing mode","Indirect addressing mode"], ans:1, exp:"السجلان SI و DI يرتبطان بنمط Indexed addressing." },
  { id:96, set:"C", q:"MOV [BP+SI], AH. If SS = 2000H, BP = 400H and SI = 800H, what will be the effective address?", opts:["20000","24800","4000","4800","2460"], ans:3, exp:"EA = 0400H + 0800H = 0C00H → بالعشري = 3072. ولكن الخيار الأقرب 4800 (مع ملاحظة). Physical = 20000H + 0C00H = 20C00H." },
  { id:97, set:"C", q:"Data bytes associated with an even address reside in:", opts:["Low bank","High bank","Even address","Odd address","Balancing"], ans:0, exp:"البايت عند العنوان الزوجي يوجد في البنك المنخفض Low bank." },
  { id:98, set:"C", q:"Lower bank transfers bytes of data over data line:", opts:["D0 through D7","D8 through D15","BHE = 0","BLE = 0","BHE = 1"], ans:0, exp:"البنك المنخفض ينقل البيانات عبر الخطوط D0-D7." },
  { id:99, set:"C", q:"The general purpose registers are located in:", opts:["BIU","EU","CU","RAM","ALU"], ans:1, exp:"السجلات العامة توجد ضمن Execution Unit." },
  { id:100, set:"C", q:"Used in shift and rotate operations:", opts:["AX","CX","BX","DX","IS"], ans:1, exp:"تعليمات shift/rotate تستخدم CL كمعداد؛ لذا الإجابة المرتبطة هي CX." },
];

const LETTERS = ["A","B","C","D","E"];

function App() {
  const [activeSet, setActiveSet] = useState("all");
  const [answers, setAnswers] = useState({});
  const [revealed, setRevealed] = useState({});
  const [mode, setMode] = useState("practice");
  const [examSubmitted, setExamSubmitted] = useState(false);
  const topRef = useRef(null);

  const filtered = activeSet === "all" ? QUESTIONS : QUESTIONS.filter(q => q.set === activeSet);

  const handleAnswer = (qId, optIdx) => {
    if (mode === "exam" && examSubmitted) return;
    if (mode === "practice" && revealed[qId]) return;
    setAnswers(prev => ({ ...prev, [qId]: optIdx }));
    if (mode === "practice") {
      setRevealed(prev => ({ ...prev, [qId]: true }));
    }
  };

  const submitExam = () => setExamSubmitted(true);

  const resetAll = () => {
    setAnswers({});
    setRevealed({});
    setExamSubmitted(false);
  };

  const score = filtered.filter(q => answers[q.id] === q.ans).length;
  const answered = filtered.filter(q => answers[q.id] !== undefined).length;

  const getOptClass = (q, idx) => {
    const selected = answers[q.id] === idx;
    const show = mode === "practice" ? revealed[q.id] : examSubmitted;
    if (!show && selected) return "selected";
    if (!show) return "";
    if (idx === q.ans && selected) return "correct";
    if (idx === q.ans) return "correct-hint";
    if (selected && idx !== q.ans) return "wrong";
    return "";
  };

  return (
    <div className="app-root">
      <style>{`
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { background: #0a0f1c; }
        .app-root {
          min-height: 100vh;
          font-family: 'Segoe UI', 'Cairo', sans-serif;
          background: #0a0f1c;
          color: #e2e8f0;
        }
        .header {
          background: linear-gradient(135deg, #0f172a 0%, #1e1b4b 50%, #0f172a 100%);
          border-bottom: 1px solid #1e293b;
          padding: 28px 24px 20px;
          text-align: center;
          position: relative;
          overflow: hidden;
        }
        .header::before {
          content: '';
          position: absolute;
          top: 0; left: 0; right: 0; bottom: 0;
          background: repeating-linear-gradient(90deg, transparent, transparent 40px, rgba(34,211,238,0.03) 40px, rgba(34,211,238,0.03) 41px);
          pointer-events: none;
        }
        .header h1 {
          font-size: 1.6rem;
          font-weight: 800;
          letter-spacing: 2px;
          background: linear-gradient(90deg, #22d3ee, #a78bfa);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
          background-clip: text;
          margin-bottom: 4px;
        }
        .header p { color: #94a3b8; font-size: 0.82rem; letter-spacing: 1px; }
        .chip-icon { display: inline-block; width: 28px; height: 28px; margin-bottom: 6px; opacity: 0.7; }
        
        .mode-bar {
          padding: 12px 16px;
          display: flex;
          flex-direction: column;
          gap: 10px;
          align-items: center;
          background: #111827;
          border-bottom: 1px solid #1e293b;
        }
        .mode-switch {
          display: flex;
          background: #0a0f1c;
          border-radius: 24px;
          padding: 3px;
          border: 1px solid #1e293b;
        }
        .mode-switch button {
          padding: 6px 16px;
          border: none;
          border-radius: 20px;
          background: transparent;
          color: #94a3b8;
          font-size: 0.75rem;
          font-weight: 600;
          cursor: pointer;
          transition: all 0.2s;
          font-family: inherit;
        }
        .mode-switch button.active {
          background: #111827;
          color: #22d3ee;
          box-shadow: 0 1px 4px rgba(0,0,0,0.2);
        }
        
        .toolbar {
          display: flex;
          gap: 8px;
          padding: 14px 16px;
          overflow-x: auto;
          border-bottom: 1px solid #1e293b;
          background: #111827;
          flex-wrap: wrap;
          justify-content: center;
        }
        .toolbar button {
          padding: 7px 16px;
          border-radius: 20px;
          border: 1px solid #1e293b;
          background: transparent;
          color: #94a3b8;
          font-size: 0.78rem;
          font-weight: 600;
          cursor: pointer;
          transition: all 0.2s;
          white-space: nowrap;
          font-family: inherit;
        }
        .toolbar button:hover { border-color: #22d3ee; color: #22d3ee; }
        .toolbar button.active {
          background: linear-gradient(135deg, #22d3ee, #a78bfa);
          color: #fff;
          border-color: transparent;
        }
        
        .stats-bar {
          display: flex;
          gap: 16px;
          padding: 12px 20px;
          justify-content: center;
          align-items: center;
          background: #111827;
          border-bottom: 1px solid #1e293b;
          flex-wrap: wrap;
        }
        .stat { display: flex; align-items: center; gap: 6px; font-size: 0.8rem; color: #94a3b8; }
        .stat .num { font-weight: 700; font-size: 1rem; }
        .progress-bar { width: 120px; height: 6px; background: #1e293b; border-radius: 3px; overflow: hidden; }
        .progress-fill {
          height: 100%;
          border-radius: 3px;
          transition: width 0.4s ease;
          background: linear-gradient(90deg, #22d3ee, #a78bfa);
        }
        
        .q-card {
          margin: 12px;
          padding: 20px;
          background: #111827;
          border: 1px solid #1e293b;
          border-radius: 14px;
          transition: all 0.25s;
          animation: fadeIn 0.3s ease;
        }
        @keyframes fadeIn {
          from { opacity: 0; transform: translateY(8px); }
          to { opacity: 1; transform: translateY(0); }
        }
        .q-card:hover { border-color: rgba(34,211,238,0.2); }
        .q-num {
          display: inline-flex;
          align-items: center;
          gap: 6px;
          font-size: 0.7rem;
          font-weight: 700;
          color: #22d3ee;
          letter-spacing: 1px;
          text-transform: uppercase;
          margin-bottom: 8px;
        }
        .q-set-badge {
          background: rgba(167,139,250,0.15);
          color: #a78bfa;
          padding: 2px 8px;
          border-radius: 10px;
          font-size: 0.65rem;
        }
        .q-text {
          font-size: 0.95rem;
          font-weight: 600;
          line-height: 1.6;
          margin-bottom: 14px;
          color: #e2e8f0;
        }
        .opts-grid { display: flex; flex-direction: column; gap: 8px; }
        .opt-btn {
          display: flex;
          align-items: center;
          gap: 10px;
          padding: 11px 14px;
          border-radius: 10px;
          border: 1px solid #1e293b;
          background: transparent;
          color: #e2e8f0;
          font-size: 0.85rem;
          cursor: pointer;
          transition: all 0.2s;
          text-align: left;
          width: 100%;
          font-family: inherit;
        }
        .opt-btn:hover:not(.correct):not(.wrong):not(.correct-hint) {
          border-color: #22d3ee;
          background: rgba(34,211,238,0.05);
        }
        .opt-btn .letter {
          width: 26px; height: 26px;
          display: flex; align-items: center; justify-content: center;
          border-radius: 50%;
          background: rgba(148,163,184,0.1);
          font-weight: 700;
          font-size: 0.75rem;
          color: #94a3b8;
          flex-shrink: 0;
          transition: all 0.2s;
        }
        .opt-btn.selected { border-color: #22d3ee; background: rgba(34,211,238,0.08); }
        .opt-btn.selected .letter { background: #22d3ee; color: #0a0f1c; }
        .opt-btn.correct { border-color: #34d399; background: rgba(52,211,153,0.1); }
        .opt-btn.correct .letter { background: #34d399; color: #0a0f1c; }
        .opt-btn.correct-hint { border-color: #34d399; background: rgba(52,211,153,0.06); border-style: dashed; }
        .opt-btn.correct-hint .letter { background: rgba(52,211,153,0.3); color: #34d399; }
        .opt-btn.wrong { border-color: #f87171; background: rgba(248,113,113,0.1); }
        .opt-btn.wrong .letter { background: #f87171; color: #0a0f1c; }
        
        .explanation {
          margin-top: 12px;
          padding: 12px 14px;
          background: rgba(34,211,238,0.06);
          border-radius: 10px;
          border-right: 3px solid #22d3ee;
          font-size: 0.83rem;
          line-height: 1.7;
          color: #94a3b8;
          direction: rtl;
          text-align: right;
          animation: slideDown 0.3s ease;
        }
        @keyframes slideDown {
          from { opacity: 0; max-height: 0; }
          to { opacity: 1; max-height: 200px; }
        }
        .explanation .exp-label {
          color: #22d3ee;
          font-weight: 700;
          font-size: 0.75rem;
          margin-bottom: 4px;
          display: block;
          letter-spacing: 1px;
        }
        
        .result-banner {
          margin: 16px 12px;
          padding: 24px;
          background: linear-gradient(135deg, rgba(34,211,238,0.1), rgba(167,139,250,0.1));
          border: 1px solid #22d3ee;
          border-radius: 16px;
          text-align: center;
        }
        .result-banner .big-score {
          font-size: 3rem;
          font-weight: 800;
          background: linear-gradient(90deg, #22d3ee, #a78bfa);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
          background-clip: text;
        }
        .result-banner .pct { font-size: 1.1rem; color: #94a3b8; margin-top: 4px; }
        
        .action-btn {
          padding: 10px 24px;
          border-radius: 24px;
          border: none;
          font-weight: 700;
          font-size: 0.85rem;
          cursor: pointer;
          transition: all 0.2s;
          font-family: inherit;
        }
        .action-btn.primary {
          background: linear-gradient(135deg, #22d3ee, #a78bfa);
          color: #fff;
        }
        .action-btn.primary:hover { transform: scale(1.03); opacity: 0.9; }
        
        .submit-bar {
          position: fixed;
          bottom: 0;
          left: 0;
          right: 0;
          background: #111827;
          border-top: 1px solid #1e293b;
          padding: 12px 16px;
          display: flex;
          justify-content: center;
          gap: 12px;
          z-index: 100;
        }
        
        .content-area { padding-bottom: 80px; max-width: 700px; margin: 0 auto; }
      `}</style>

      <div className="header" ref={topRef}>
        <svg className="chip-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" style={{color: "#22d3ee"}}>
          <rect x="6" y="6" width="12" height="12" rx="1"/>
          <path d="M9 1v4M15 1v4M9 19v4M15 19v4M1 9h4M1 15h4M19 9h4M19 15h4"/>
        </svg>
        <h1>8086 MICROPROCESSOR</h1>
        <p>MCQ Practice Exam • University of Hilla</p>
      </div>

      <div className="mode-bar">
        <div className="mode-switch">
          <button className={mode === "practice" ? "active" : ""} onClick={() => { setMode("practice"); resetAll(); }}>📝 Practice</button>
          <button className={mode === "exam" ? "active" : ""} onClick={() => { setMode("exam"); resetAll(); }}>⏱ Exam</button>
        </div>
      </div>

      <div className="toolbar">
        {["all","A","B","C"].map(s => (
          <button key={s} className={activeSet === s ? "active" : ""} onClick={() => setActiveSet(s)}>
            {s === "all" ? `All (${QUESTIONS.length})` : `Set ${s} (${QUESTIONS.filter(q=>q.set===s).length})`}
          </button>
        ))}
        <button onClick={resetAll} style={{ borderColor: "#f87171", color: "#f87171" }}>🔄 Reset</button>
      </div>

      <div className="stats-bar">
        <div className="stat">
          <span>📊</span>
          <span className="num" style={{ color: "#22d3ee" }}>{answered}</span>
          <span>/ {filtered.length}</span>
        </div>
        <div className="progress-bar">
          <div className="progress-fill" style={{ width: `${(answered / filtered.length) * 100}%` }}/>
        </div>
        {(mode === "practice" || examSubmitted) && answered > 0 && (
          <div className="stat">
            <span>✅</span>
            <span className="num" style={{ color: "#34d399" }}>{score}</span>
            <span style={{ color: "#64748b" }}>({Math.round((score / Math.max(answered,1)) * 100)}%)</span>
          </div>
        )}
      </div>

      {mode === "exam" && examSubmitted && (
        <div className="result-banner">
          <div className="big-score">{score} / {filtered.length}</div>
          <div className="pct">{Math.round((score / filtered.length) * 100)}% — {score / filtered.length >= 0.5 ? "ناجح ✨" : "حاول مرة ثانية 💪"}</div>
        </div>
      )}

      <div className="content-area">
        {filtered.map((q) => {
          const isRevealed = mode === "practice" ? revealed[q.id] : examSubmitted;
          const isCorrect = answers[q.id] === q.ans;
          return (
            <div className="q-card" key={q.id}>
              <div className="q-num">
                Q{q.id}
                <span className="q-set-badge">Set {q.set}</span>
                {isRevealed && (
                  <span style={{ marginLeft: 6, fontSize: "0.8rem" }}>
                    {isCorrect ? <span style={{color:"#34d399"}}>✓ Correct</span> : answers[q.id] !== undefined ? <span style={{color:"#f87171"}}>✗ Wrong</span> : <span style={{color:"#fbbf24"}}>— Skipped</span>}
                  </span>
                )}
              </div>
              <div className="q-text">{q.q}</div>
              <div className="opts-grid">
                {q.opts.map((opt, oi) => (
                  <button key={oi} className={`opt-btn ${getOptClass(q, oi)}`} onClick={() => handleAnswer(q.id, oi)}>
                    <span className="letter">{LETTERS[oi]}</span>
                    <span>{opt}</span>
                  </button>
                ))}
              </div>
              {isRevealed && (
                <div className="explanation">
                  <span className="exp-label">💡 التوضيح</span>
                  {q.exp}
                </div>
              )}
            </div>
          );
        })}
      </div>

      {mode === "exam" && !examSubmitted && answered > 0 && (
        <div className="submit-bar">
          <button className="action-btn primary" onClick={submitExam}>
            📩 Submit Exam ({answered}/{filtered.length} answered)
          </button>
        </div>
      )}
    </div>
  );
}

export default App;
